import React,{useEffect,useState}from"react";
import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{getPatientHomeVisits,getPatientFollowUps,getNotifications,NotificationItem}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"Activity">;
export default function ActivityScreen({navigation}:Props){const[v,setV]=useState<any[]>([]),[f,setF]=useState<any[]>([]),[n,setN]=useState<NotificationItem[]>([]);useEffect(()=>{Promise.all([getPatientHomeVisits(),getPatientFollowUps(),getNotifications()]).then(([a,b,c])=>{setV(a);setF(b);setN(c)}).catch(e=>Alert.alert("CareLink",e.message));},[]);return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={styles.title}>Your care activity</Text><Text style={styles.section}>Notifications</Text>{n.map(x=><View style={styles.card}key={x.id}><Text style={styles.name}>{x.title}</Text><Text style={styles.meta}>{x.body}</Text></View>)}<Text style={styles.section}>Home-care requests</Text>{v.map(x=><View style={styles.card}key={x.id}><Text style={styles.name}>{x.reason}</Text><Text style={styles.meta}>{x.address}</Text><Text style={styles.status}>{x.status}</Text></View>)}<Text style={styles.section}>Follow-ups</Text>{f.map(x=><View style={styles.card}key={x.id}><Text style={styles.name}>{new Date(x.scheduled_at).toLocaleString()}</Text><Text style={styles.meta}>{x.note}</Text><Text style={styles.status}>{x.completed?"Completed":"Scheduled"}</Text></View>)}{!n.length&&!v.length&&!f.length&&<Text style={styles.empty}>No care activity yet.</Text>}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl},section:{fontSize:20,fontWeight:"800",color:colors.text,marginTop:spacing.xl,marginBottom:spacing.md},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,marginBottom:spacing.sm},name:{fontWeight:"800",fontSize:17,color:colors.text},meta:{color:colors.muted,marginTop:5},status:{color:colors.primaryDark,fontWeight:"800",marginTop:8},empty:{color:colors.muted}});
