import React,{useState}from"react";
import{Alert,Pressable,SafeAreaView,StyleSheet,Text,TextInput}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{requestHomeVisit}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"HomeVisit">;
export default function HomeVisitScreen({navigation}:Props){const[address,setAddress]=useState("");const[reason,setReason]=useState("");const[busy,setBusy]=useState(false);async function submit(){if(address.trim().length<5||reason.trim().length<3)return Alert.alert("CareLink","Enter your home address and reason.");setBusy(true);try{await requestHomeVisit(address.trim(),reason.trim());Alert.alert("CareLink","Home-care request submitted.");navigation.navigate("Activity");}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to submit request.");}finally{setBusy(false)}}return <SafeAreaView style={styles.safe}><Text style={styles.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={styles.brand}>CareLink <Text style={styles.ai}>AI</Text></Text><Text style={styles.title}>Request home care</Text><Text style={styles.subtitle}>Tell us where care is needed and what support you need.</Text><Text style={styles.label}>Home address</Text><TextInput style={styles.input}value={address}onChangeText={setAddress}placeholder="Your address"/><Text style={styles.label}>Reason for home care</Text><TextInput style={[styles.input,styles.multi]}multiline value={reason}onChangeText={setReason}placeholder="Describe the support you need"/><Pressable style={styles.primary}onPress={submit}disabled={busy}><Text style={styles.primaryText}>{busy?"Submitting...":"Request home care"}</Text></Pressable></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background,padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},brand:{fontSize:21,fontWeight:"800",color:colors.text,marginTop:spacing.lg},ai:{color:colors.primary},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl},subtitle:{color:colors.muted,lineHeight:22,marginTop:spacing.sm},label:{fontWeight:"800",color:colors.text,marginTop:spacing.xl,marginBottom:spacing.xs},input:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:15},multi:{minHeight:120,textAlignVertical:"top"},primary:{backgroundColor:colors.primary,borderRadius:radius.pill,paddingVertical:16,alignItems:"center",marginTop:spacing.xl},primaryText:{color:"#fff",fontWeight:"800",fontSize:16}});
