import React,{useEffect,useState}from"react";
import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{createThread,getMessages,sendMessage,MessageItem}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"Messages">;
export default function MessagesScreen({route,navigation}:Props){const[thread,setThread]=useState<number|null>(null),[items,setItems]=useState<MessageItem[]>([]),[body,setBody]=useState("");useEffect(()=>{createThread(route.params.providerId).then(t=>{setThread(t.id);return getMessages(t.id)}).then(setItems).catch(e=>Alert.alert("CareLink",e.message));},[]);async function send(){if(!thread||!body.trim())return;try{const m=await sendMessage(thread,body.trim());setItems(x=>[...x,m]);setBody("")}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to send message.")}}return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={styles.title}>Message provider</Text><Text style={styles.subtitle}>{route.params.providerName}</Text>{items.map(m=><View key={m.id}style={styles.bubble}><Text style={styles.message}>{m.body}</Text></View>)}{!items.length&&<Text style={styles.empty}>Start a secure care conversation.</Text>}</ScrollView><View style={styles.composer}><TextInput style={styles.input}value={body}onChangeText={setBody}placeholder="Write a message"/><Pressable style={styles.send}onPress={send}><Text style={styles.sendText}>Send</Text></Pressable></View></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},title:{fontSize:28,fontWeight:"800",color:colors.text,marginTop:spacing.xl},subtitle:{color:colors.muted,marginTop:4,marginBottom:spacing.lg},bubble:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,marginBottom:spacing.sm},message:{color:colors.text,lineHeight:21},empty:{color:colors.muted},composer:{flexDirection:"row",padding:spacing.md,borderTopWidth:1,borderColor:colors.border,backgroundColor:colors.surface,gap:spacing.sm},input:{flex:1,borderWidth:1,borderColor:colors.border,borderRadius:radius.pill,paddingHorizontal:16},send:{backgroundColor:colors.primary,borderRadius:radius.pill,paddingHorizontal:18,justifyContent:"center"},sendText:{color:"#fff",fontWeight:"800"}});
