import React,{useState}from"react";
import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{nurseCheckIn,nurseCheckOut,saveNurseCareRecord}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"NurseCare">;
export default function NurseCareScreen({navigation,route}:Props){const[vitals,setVitals]=useState("");const[observations,setObservations]=useState("");const[interventions,setInterventions]=useState("");const[escalation,setEscalation]=useState("");async function run(fn:()=>Promise<unknown>,msg:string){try{await fn();Alert.alert("CareLink",msg)}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Action failed")}}return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={s.title}>Nursing home visit</Text><Pressable style={s.primary}onPress={()=>run(()=>nurseCheckIn(route.params.visitId),"Check-in recorded.")}><Text style={s.primaryText}>Check in</Text></Pressable><TextInput style={s.input}multiline placeholder="Vitals / measurements" value={vitals}onChangeText={setVitals}/><TextInput style={s.input}multiline placeholder="Observations" value={observations}onChangeText={setObservations}/><TextInput style={s.input}multiline placeholder="Interventions / care provided" value={interventions}onChangeText={setInterventions}/><TextInput style={s.input}multiline placeholder="Escalation note, if further assessment is required" value={escalation}onChangeText={setEscalation}/><Pressable style={s.primary}onPress={()=>run(()=>saveNurseCareRecord(route.params.visitId,{vitals,observations,interventions,escalation_required:!!escalation,escalation_note:escalation||undefined}),"Care record saved.")}><Text style={s.primaryText}>Save care record</Text></Pressable><Pressable style={s.secondary}onPress={()=>run(()=>nurseCheckOut(route.params.visitId),"Visit completed.")}><Text style={s.secondaryText}>Check out & complete</Text></Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},title:{fontSize:30,fontWeight:"800",color:colors.text,marginVertical:spacing.xl},input:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:15,minHeight:80,textAlignVertical:"top",marginTop:spacing.md},primary:{backgroundColor:colors.primary,borderRadius:radius.pill,padding:15,alignItems:"center",marginTop:spacing.md},primaryText:{color:"#fff",fontWeight:"800"},secondary:{borderWidth:1,borderColor:colors.border,borderRadius:radius.pill,padding:15,alignItems:"center",marginTop:spacing.md},secondaryText:{color:colors.primaryDark,fontWeight:"800"}});
