import React,{useState}from"react";
import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{createProviderProfile}from"../api/client";
import{useAuth}from"../auth/AuthContext";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"ProviderSetup">;
export default function ProviderSetupScreen({navigation}:Props){const{user,refreshProfile}=useAuth();const[type]=useState(user?.role||"doctor");const[specialty,setSpecialty]=useState("");const[license,setLicense]=useState("");const[phone,setPhone]=useState("");const[facility,setFacility]=useState("");const[city,setCity]=useState("");const[bio,setBio]=useState("");const[busy,setBusy]=useState(false);async function submit(){if(!specialty.trim()||!license.trim())return Alert.alert("CareLink","Specialty and professional license number are required.");setBusy(true);try{await createProviderProfile({provider_type:type,specialty,license_number:license,phone,facility_name:facility,city,bio});await refreshProfile();navigation.reset({index:0,routes:[{name:"ProviderHome"}]});}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to create provider profile.");}finally{setBusy(false)}}return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.brand}>CareLink <Text style={styles.ai}>AI</Text></Text><Text style={styles.title}>Professional profile</Text><Text style={styles.subtitle}>Complete your provider profile. Verification remains a separate professional review step.</Text><Text style={styles.label}>Role</Text><Text style={styles.readonly}>{type}</Text><Text style={styles.label}>Specialty</Text><TextInput style={styles.input}value={specialty}onChangeText={setSpecialty}placeholder="e.g. General Practice"/><Text style={styles.label}>License number</Text><TextInput style={styles.input}value={license}onChangeText={setLicense}placeholder="Professional license number"/><Text style={styles.label}>Phone</Text><TextInput style={styles.input}value={phone}onChangeText={setPhone}placeholder="Phone number"/><Text style={styles.label}>Facility</Text><TextInput style={styles.input}value={facility}onChangeText={setFacility}placeholder="Hospital or clinic"/><Text style={styles.label}>City</Text><TextInput style={styles.input}value={city}onChangeText={setCity}placeholder="Abuja"/><Text style={styles.label}>Professional bio</Text><TextInput style={[styles.input,styles.multi]}multiline value={bio}onChangeText={setBio}placeholder="Short professional introduction"/><Pressable style={styles.primary}onPress={submit}disabled={busy}><Text style={styles.primaryText}>{busy?"Saving...":"Continue to provider workspace"}</Text></Pressable></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},brand:{fontSize:21,fontWeight:"800",color:colors.text},ai:{color:colors.primary},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl},subtitle:{color:colors.muted,lineHeight:22,marginTop:spacing.sm},label:{fontWeight:"800",color:colors.text,marginTop:spacing.lg,marginBottom:spacing.xs},readonly:{backgroundColor:colors.blueSoft,borderRadius:radius.md,padding:15,color:colors.text,textTransform:"capitalize"},input:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:15,fontSize:16},multi:{minHeight:100,textAlignVertical:"top"},primary:{backgroundColor:colors.primary,borderRadius:radius.pill,paddingVertical:16,alignItems:"center",marginTop:spacing.xl},primaryText:{color:"#fff",fontWeight:"800",fontSize:16}});
