import React,{useEffect,useState}from"react";
import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{getProviderAppointments,updateProviderAppointment}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"ProviderAppointments">;
export default function ProviderAppointmentsScreen({navigation}:Props){const[data,setData]=useState<any[]>([]);async function load(){try{setData(await getProviderAppointments())}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to load appointments.")}}useEffect(()=>{load()},[]);async function update(id:number,status:string){try{await updateProviderAppointment(id,status);await load()}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to update appointment.")}}return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={styles.title}>Appointments</Text>{data.map(x=><View style={styles.card}key={x.id}><Text style={styles.name}>{new Date(x.scheduled_at).toLocaleString()}</Text><Text style={styles.meta}>{x.reason}</Text><Text style={styles.status}>{x.status}</Text>{x.status==="requested"&&<Pressable style={styles.primary}onPress={()=>update(x.id,"confirmed")}><Text style={styles.primaryText}>Confirm</Text></Pressable>}{x.status==="confirmed"&&<Pressable style={styles.primary}onPress={()=>update(x.id,"completed")}><Text style={styles.primaryText}>Mark completed</Text></Pressable>}</View>)}{!data.length&&<Text style={styles.empty}>No appointment requests yet.</Text>}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl,marginBottom:spacing.lg},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,marginBottom:spacing.sm},name:{fontWeight:"800",fontSize:17,color:colors.text},meta:{color:colors.muted,marginTop:5},status:{color:colors.primaryDark,fontWeight:"800",marginTop:8},primary:{backgroundColor:colors.primary,borderRadius:radius.pill,paddingVertical:12,alignItems:"center",marginTop:spacing.md},primaryText:{color:"#fff",fontWeight:"800"},empty:{color:colors.muted}});
