import React,{useEffect,useState}from"react";
import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{getProviderAISummaries}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"ProviderSummaries">;
export default function ProviderSummariesScreen({navigation}:Props){const[data,setData]=useState<any[]>([]);useEffect(()=>{getProviderAISummaries().then(setData).catch(e=>Alert.alert("CareLink",e instanceof Error?e.message:"Unable to load summaries."))},[]);return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={styles.title}>AI patient summaries</Text><Text style={styles.subtitle}>Structured patient-reported information for professional review. It is not a diagnosis.</Text>{data.map(x=><View style={styles.card}key={x.intake_id}><Text style={styles.name}>{x.patient_name}</Text><Text style={styles.status}>Urgency: {x.urgency}</Text><Text style={styles.label}>Reported concern</Text><Text style={styles.text}>{x.symptoms}</Text><Text style={styles.label}>Summary</Text><Text style={styles.text}>{x.summary}</Text><Text style={styles.label}>Clinician handoff</Text><Text style={styles.text}>{x.clinician_handoff}</Text></View>)}{!data.length&&<Text style={styles.empty}>No patient AI intake summaries yet.</Text>}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl},subtitle:{color:colors.muted,lineHeight:21,marginTop:6},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,marginTop:spacing.lg},name:{fontSize:18,fontWeight:"800",color:colors.text},status:{color:colors.primaryDark,fontWeight:"800",marginTop:6},label:{fontWeight:"800",color:colors.text,marginTop:spacing.md},text:{color:colors.muted,lineHeight:21,marginTop:4},empty:{color:colors.muted,marginTop:spacing.lg}});
