import React,{useEffect,useState}from"react";
import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{completeProviderFollowUp,getProviderFollowUps,getProviderNotifications,FollowUp,NotificationItem}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"ProviderActivity">;
export default function ProviderActivityScreen({navigation}:Props){const[n,setN]=useState<NotificationItem[]>([]),[f,setF]=useState<FollowUp[]>([]);async function load(){try{const[a,b]=await Promise.all([getProviderNotifications(),getProviderFollowUps()]);setN(a);setF(b)}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to load activity.")}}useEffect(()=>{load()},[]);async function complete(id:number){try{await completeProviderFollowUp(id);await load()}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to complete follow-up.")}}return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={styles.title}>Provider activity</Text><Text style={styles.section}>Notifications</Text>{n.map(x=><View style={styles.card}key={x.id}><Text style={styles.name}>{x.title}</Text><Text style={styles.meta}>{x.body}</Text></View>)}<Text style={styles.section}>Follow-ups</Text>{f.map(x=><View style={styles.card}key={x.id}><Text style={styles.name}>{new Date(x.scheduled_at).toLocaleString()}</Text><Text style={styles.meta}>{x.note}</Text>{!x.completed&&<Pressable style={styles.primary}onPress={()=>complete(x.id)}><Text style={styles.primaryText}>Mark completed</Text></Pressable>}<Text style={styles.status}>{x.completed?"Completed":"Scheduled"}</Text></View>)}{!n.length&&!f.length&&<Text style={styles.empty}>No provider activity yet.</Text>}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl},section:{fontSize:20,fontWeight:"800",color:colors.text,marginTop:spacing.xl,marginBottom:spacing.md},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,marginBottom:spacing.sm},name:{fontWeight:"800",fontSize:17,color:colors.text},meta:{color:colors.muted,marginTop:5},status:{color:colors.primaryDark,fontWeight:"800",marginTop:8},primary:{backgroundColor:colors.primary,borderRadius:radius.pill,paddingVertical:12,alignItems:"center",marginTop:spacing.md},primaryText:{color:"#fff",fontWeight:"800"},empty:{color:colors.muted}});
