import React,{useEffect,useState}from"react";
import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{getProviderMessages,getProviderThreads,getMessages,sendProviderMessage,ProviderThread,MessageItem}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"ProviderMessages">;
export default function ProviderMessagesScreen({navigation}:Props){const[threads,setThreads]=useState<ProviderThread[]>([]);const[selected,setSelected]=useState<number|null>(null);const[messages,setMessages]=useState<MessageItem[]>([]);const[body,setBody]=useState("");useEffect(()=>{getProviderThreads().then(setThreads).catch(e=>Alert.alert("CareLink",e.message))},[]);async function select(id:number){setSelected(id);try{setMessages(await getProviderMessages(id))}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to load conversation.")}}async function send(){if(!selected||!body.trim())return;try{const m=await sendProviderMessage(selected,body.trim());setMessages(x=>[...x,m]);setBody("")}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to send message.")}}return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={styles.title}>Patient messages</Text>{threads.map(t=><Pressable key={t.id}style={[styles.thread,selected===t.id&&styles.selected]}onPress={()=>select(t.id)}><Text style={styles.name}>Patient #{t.patient_id}</Text><Text style={styles.meta}>Conversation {t.id}</Text></Pressable>)}{selected&&<View style={styles.chat}>{messages.map(m=><View key={m.id}style={styles.bubble}><Text style={styles.message}>{m.body}</Text></View>)}<View style={styles.composer}><TextInput style={styles.input}value={body}onChangeText={setBody}placeholder="Reply to patient"/><Pressable style={styles.send}onPress={send}><Text style={styles.sendText}>Send</Text></Pressable></View></View>}{!threads.length&&<Text style={styles.empty}>No patient conversations yet.</Text>}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl,marginBottom:spacing.lg},thread:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,marginBottom:spacing.sm},selected:{borderColor:colors.primary,backgroundColor:colors.blueSoft},name:{fontWeight:"800",color:colors.text},meta:{color:colors.muted,marginTop:4},chat:{marginTop:spacing.lg},bubble:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,marginBottom:spacing.sm},message:{color:colors.text},composer:{flexDirection:"row",gap:spacing.sm,marginTop:spacing.sm},input:{flex:1,borderWidth:1,borderColor:colors.border,borderRadius:radius.pill,paddingHorizontal:16,backgroundColor:colors.surface},send:{backgroundColor:colors.primary,borderRadius:radius.pill,paddingHorizontal:18,justifyContent:"center"},sendText:{color:"#fff",fontWeight:"800"},empty:{color:colors.muted}});
