import React,{useEffect,useState}from"react";
import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{getProviderQuality,getProviderReviews,ProviderQuality,ProviderReview}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"ProviderDetails">;
export default function ProviderDetailsScreen({navigation,route}:Props){const{provider}=route.params;const[q,setQ]=useState<ProviderQuality|null>(null);const[r,setR]=useState<ProviderReview[]>([]);useEffect(()=>{Promise.all([getProviderQuality(provider.id),getProviderReviews(provider.id)]).then(([a,b])=>{setQ(a);setR(b)}).catch(e=>Alert.alert("CareLink",e instanceof Error?e.message:"Unable to load provider quality."))},[provider.id]);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={s.title}>{provider.full_name}</Text><Text style={s.verified}>✓ CareLink verified</Text><View style={s.card}><Text style={s.name}>{provider.professional_title||provider.provider_type} · {provider.specialty||"General care"}</Text><Text style={s.meta}>{provider.gender||"Gender not listed"} · {provider.age?"Age "+provider.age:"Age not listed"} · {provider.city||"Location not listed"}</Text><Text style={s.meta}>{provider.years_experience??0} years experience · {provider.cases_completed} completed CareLink cases</Text><Text style={s.meta}>{provider.languages||"Languages not listed"}</Text><Text style={s.meta}>{provider.qualifications||"Qualifications pending profile update"}</Text><Text style={s.rating}>★ {provider.average_rating??"New"} · {provider.review_count} reviews</Text></View>{q&&<View style={s.card}><Text style={s.name}>Quality & reliability</Text><Text style={s.meta}>Appointments completed: {q.appointments_completed}</Text><Text style={s.meta}>Home visits completed: {q.home_visits_completed}</Text><Text style={s.meta}>Cancellations: {q.cancellation_count}</Text><Text style={s.meta}>Service issues recorded: {q.complaint_count}</Text></View>}<Pressable style={s.primary}onPress={()=>navigation.navigate("Booking",{providerId:provider.id,providerName:provider.full_name})}><Text style={s.primaryText}>Request appointment</Text></Pressable><Pressable style={s.secondary}onPress={()=>navigation.navigate("Messages",{providerId:provider.id,providerName:provider.full_name})}><Text style={s.secondaryText}>Message provider</Text></Pressable><Text style={s.section}>Verified patient reviews</Text>{r.map(x=><View key={x.id}style={s.card}><Text style={s.rating}>Rating: {x.rating}/5</Text>{x.comment&&<Text style={s.meta}>{x.comment}</Text>}</View>)}{!r.length&&<Text style={s.meta}>No completed-care reviews yet.</Text>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl},verified:{color:colors.primaryDark,fontWeight:"800",marginTop:6},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,marginTop:spacing.md},name:{fontWeight:"800",fontSize:17,color:colors.text},meta:{color:colors.muted,marginTop:6,lineHeight:20},rating:{fontWeight:"800",color:colors.primaryDark,marginTop:8},primary:{backgroundColor:colors.primary,borderRadius:radius.pill,padding:15,alignItems:"center",marginTop:spacing.lg},primaryText:{color:"#fff",fontWeight:"800"},secondary:{borderWidth:1,borderColor:colors.border,borderRadius:radius.pill,padding:15,alignItems:"center",marginTop:spacing.sm},secondaryText:{color:colors.primaryDark,fontWeight:"800"},section:{fontSize:20,fontWeight:"800",color:colors.text,marginTop:spacing.xl}});
