import React,{useEffect,useState}from"react";
import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{addProviderAvailability,getProviderAvailability,getProviderProfile,ProviderAvailability,ProviderProfile}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"ProviderProfile">;
export default function ProviderProfileScreen({navigation}:Props){const[p,setP]=useState<ProviderProfile|null>(null);const[a,setA]=useState<ProviderAvailability[]>([]);const[day,setDay]=useState("1");const[start,setStart]=useState("09:00");const[end,setEnd]=useState("17:00");useEffect(()=>{Promise.all([getProviderProfile(),getProviderAvailability()]).then(([x,y])=>{setP(x);setA(y)}).catch(e=>Alert.alert("CareLink",e.message))},[]);async function add(){try{const x=await addProviderAvailability({day_of_week:Number(day),start_time:start,end_time:end});setA(v=>[...v,x])}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to add availability.")}}return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={styles.title}>Professional profile</Text>{p&&<View style={styles.card}><Text style={styles.name}>{p.provider_type} · {p.specialty}</Text><Text style={styles.meta}>{p.facility_name||"Facility not set"} · {p.city||"City not set"}</Text><Text style={styles.status}>Verification: {p.verification_status}</Text></View>}<Text style={styles.section}>Availability</Text><TextInput style={styles.input}value={day}onChangeText={setDay}keyboardType="number-pad"placeholder="Day 0-6"/><TextInput style={styles.input}value={start}onChangeText={setStart}placeholder="09:00"/><TextInput style={styles.input}value={end}onChangeText={setEnd}placeholder="17:00"/><Pressable style={styles.primary}onPress={add}><Text style={styles.primaryText}>Add availability</Text></Pressable>{a.map(x=><Text style={styles.meta}key={x.id}>Day {x.day_of_week}: {x.start_time} – {x.end_time}</Text>)}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,marginTop:spacing.lg},name:{fontSize:18,fontWeight:"800",color:colors.text},meta:{color:colors.muted,marginTop:6},status:{color:colors.primaryDark,fontWeight:"800",marginTop:6},section:{fontSize:20,fontWeight:"800",color:colors.text,marginTop:spacing.xl,marginBottom:spacing.md},input:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:15,marginBottom:spacing.sm},primary:{backgroundColor:colors.primary,borderRadius:radius.pill,paddingVertical:15,alignItems:"center",marginBottom:spacing.md},primaryText:{color:"#fff",fontWeight:"800"}});
