import React,{useEffect,useState}from"react";
import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{getProviderHomeVisits,getAvailableProviderHomeVisits,claimProviderHomeVisit,updateProviderHomeVisit}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"ProviderHomeVisits">;
export default function ProviderHomeVisitsScreen({navigation}:Props){const[data,setData]=useState<any[]>([]);const[available,setAvailable]=useState<any[]>([]);async function load(){try{const [mine,open]=await Promise.all([getProviderHomeVisits(),getAvailableProviderHomeVisits()]);setData(mine);setAvailable(open)}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to load home visits.")}}useEffect(()=>{load()},[]);async function update(id:number,status:string){try{await updateProviderHomeVisit(id,status);await load()}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to update home visit.")}}return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={styles.title}>Home visits</Text><Text style={styles.section}>Available requests</Text>{available.map(x=><View style={styles.card}key={"a"+x.id}><Text style={styles.name}>{x.address}</Text><Text style={styles.meta}>{x.reason}</Text><Pressable style={styles.primary}onPress={async()=>{try{await claimProviderHomeVisit(x.id);await load()}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to claim request.")}}}><Text style={styles.primaryText}>Accept request</Text></Pressable></View>)}<Text style={styles.section}>My home visits</Text>{data.map(x=><View style={styles.card}key={x.id}><Text style={styles.name}>{x.address}</Text><Text style={styles.meta}>{x.reason}</Text><Text style={styles.status}>{x.status}</Text>{x.status==="requested"&&<Pressable style={styles.primary}onPress={()=>update(x.id,"accepted")}><Text style={styles.primaryText}>Accept request</Text></Pressable>}{x.status==="accepted"&&<Pressable style={styles.primary}onPress={()=>update(x.id,"completed")}><Text style={styles.primaryText}>Complete visit</Text></Pressable>}</View>)}{!data.length&&<Text style={styles.empty}>No home-care requests yet.</Text>}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},section:{fontSize:20,fontWeight:"800",color:colors.text,marginTop:spacing.xl,marginBottom:spacing.md},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl,marginBottom:spacing.lg},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md,marginBottom:spacing.sm},name:{fontWeight:"800",fontSize:17,color:colors.text},meta:{color:colors.muted,marginTop:5},status:{color:colors.primaryDark,fontWeight:"800",marginTop:8},primary:{backgroundColor:colors.primary,borderRadius:radius.pill,paddingVertical:12,alignItems:"center",marginTop:spacing.md},primaryText:{color:"#fff",fontWeight:"800"},empty:{color:colors.muted}});
