import React from"react";
import{Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{useAuth}from"../auth/AuthContext";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"ProviderHome">;
export default function ProviderHomeScreen({navigation}:Props){const{user,providerProfile,signOut}=useAuth();return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.brand}>CareLink <Text style={styles.ai}>AI</Text></Text><Text style={styles.greeting}>Provider workspace</Text></View><Pressable onPress={signOut}><Text style={styles.sign}>Sign out</Text></Pressable></View><View style={styles.hero}><Text style={styles.heroTitle}>Welcome, {user?.full_name.split(" ")[0]}</Text><Text style={styles.heroText}>{providerProfile?.specialty||"Healthcare provider"} · {providerProfile?.verification_status==="verified"?"Verified":"Verification pending"}</Text></View><Text style={styles.section}>Care workspace</Text><View style={styles.grid}><Pressable style={styles.card}onPress={()=>navigation.navigate("ProviderAppointments")}><Text style={styles.icon}>◷</Text><Text style={styles.name}>Appointments</Text><Text style={styles.meta}>Review and update patient requests.</Text></Pressable><Pressable style={styles.card}onPress={()=>navigation.navigate("ProviderSummaries")}><Text style={styles.icon}>✦</Text><Text style={styles.name}>AI patient summaries</Text><Text style={styles.meta}>Review structured intake before care.</Text></Pressable><Pressable style={styles.card}onPress={()=>navigation.navigate("ProviderHomeVisits")}><Text style={styles.icon}>⌂</Text><Text style={styles.name}>Home visits</Text><Text style={styles.meta}>Manage home-care requests.</Text></Pressable><Pressable style={styles.card}onPress={()=>navigation.navigate("ProviderMessages")}><Text style={styles.icon}>✉</Text><Text style={styles.name}>Patient messages</Text><Text style={styles.meta}>Secure conversations with patients.</Text></Pressable><Pressable style={styles.card}onPress={()=>navigation.navigate("ProviderProfile")}><Text style={styles.icon}>●</Text><Text style={styles.name}>Availability & profile</Text><Text style={styles.meta}>Maintain your professional details.</Text></Pressable></View></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg},header:{flexDirection:"row",justifyContent:"space-between"},brand:{fontSize:21,fontWeight:"800",color:colors.text},ai:{color:colors.primary},greeting:{fontSize:18,fontWeight:"700",color:colors.text,marginTop:4},sign:{color:colors.muted,fontWeight:"700"},hero:{backgroundColor:colors.blueSoft,borderRadius:radius.lg,padding:spacing.lg,marginTop:spacing.lg,borderWidth:1,borderColor:colors.border},heroTitle:{fontSize:26,fontWeight:"800",color:colors.text},heroText:{color:colors.muted,marginTop:6},section:{fontSize:20,fontWeight:"800",color:colors.text,marginTop:spacing.xl,marginBottom:spacing.md},grid:{gap:spacing.sm},card:{backgroundColor:colors.surface,borderRadius:radius.lg,padding:spacing.md,borderWidth:1,borderColor:colors.border},icon:{fontSize:22,color:colors.primary},name:{fontSize:17,fontWeight:"800",color:colors.text,marginTop:5},meta:{color:colors.muted,marginTop:4}});
