import React,{useState}from"react";
import{Alert,Pressable,SafeAreaView,StyleSheet,Text,TextInput}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{submitProviderComplaint}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"ReportServiceIssue">;
export default function ReportServiceIssueScreen({navigation,route}:Props){const[category,setCategory]=useState("service_issue");const[description,setDescription]=useState("");async function submit(){if(description.trim().length<5)return Alert.alert("CareLink","Please describe what happened.");try{await submitProviderComplaint({provider_id:route.params.providerId,appointment_id:route.params.appointmentId,category,description});Alert.alert("CareLink","Your service issue has been recorded for quality review.");navigation.goBack()}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to submit report.")}}return <SafeAreaView style={s.safe}><Text style={s.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={s.title}>Report a service issue</Text><Text style={s.meta}>Use categories such as provider_no_show, late_arrival, cancellation, communication, conduct, billing or safety.</Text><TextInput style={s.input}value={category}onChangeText={setCategory}placeholder="Issue category"/><TextInput style={[s.input,s.multi]}value={description}onChangeText={setDescription}multiline placeholder="Describe what happened"/><Pressable style={s.primary}onPress={submit}><Text style={s.primaryText}>Submit for quality review</Text></Pressable></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background,padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl},meta:{color:colors.muted,marginVertical:spacing.lg,lineHeight:20},input:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:15,marginBottom:spacing.md},multi:{minHeight:140,textAlignVertical:"top"},primary:{backgroundColor:colors.primary,borderRadius:radius.pill,padding:15,alignItems:"center"},primaryText:{color:"#fff",fontWeight:"800"}});
