import React,{useState}from"react";
import{Alert,Pressable,SafeAreaView,StyleSheet,Text,TextInput}from"react-native";
import{NativeStackScreenProps}from"@react-navigation/native-stack";
import{RootStackParamList}from"../../App";
import{submitProviderReview}from"../api/client";
import{colors,radius,spacing}from"../theme";
type Props=NativeStackScreenProps<RootStackParamList,"ReviewProvider">;
export default function ReviewProviderScreen({navigation,route}:Props){const[rating,setRating]=useState("5");const[comment,setComment]=useState("");async function save(){try{await submitProviderReview({appointment_id:route.params.appointmentId,rating:Number(rating),comment});Alert.alert("CareLink","Thank you. Your verified-care review was recorded.");navigation.goBack()}catch(e){Alert.alert("CareLink",e instanceof Error?e.message:"Unable to submit review.")}}return <SafeAreaView style={s.safe}><Text style={s.back}onPress={()=>navigation.goBack()}>‹ Back</Text><Text style={s.title}>Rate your care</Text><Text style={s.meta}>Only completed CareLink appointments can be reviewed.</Text><TextInput style={s.input}value={rating}onChangeText={setRating}keyboardType="number-pad"placeholder="Rating 1-5"/><TextInput style={[s.input,s.multi]}value={comment}onChangeText={setComment}multiline placeholder="Share your experience"/><Pressable style={s.primary}onPress={save}><Text style={s.primaryText}>Submit verified review</Text></Pressable></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background,padding:spacing.lg},back:{color:colors.primaryDark,fontWeight:"800"},title:{fontSize:30,fontWeight:"800",color:colors.text,marginTop:spacing.xl},meta:{color:colors.muted,marginVertical:spacing.lg},input:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:15,marginBottom:spacing.md},multi:{minHeight:120,textAlignVertical:"top"},primary:{backgroundColor:colors.primary,borderRadius:radius.pill,padding:15,alignItems:"center"},primaryText:{color:"#fff",fontWeight:"800"}});
